// AI Services — all functions return Promise<AiEnvelope<T>>
// Mock implementations with realistic confidence values.
// Swap in real LLM calls by replacing the body of each function.

export { generatePreBrief } from './pre-brief'
export { suggestDiagnoses } from './diagnosis'
export { suggestPrescription } from './prescription'
export { assessTriage } from './triage'
export { generateDischargeSummary } from './discharge-summary'
export { generateRadiologyReport } from './radiology-report'
export { detectLabAnomalies } from './lab-anomaly'
export { suggestReflexTests } from './reflex-test'
export { checkDrugInteractionsAi } from './drug-interaction'
export { forecastBedDemand } from './bed-forecast'
export { draftPreAuth } from './insurance-preauth'
export { suggestDietPlan } from './diet-plan'
export { generateOTBriefing } from './ot-briefing'
export { verifyOTChecklist } from './ot-checklist'
export { assessMortalityRisk } from './mortality-risk'
export { assessReadmissionRisk } from './readmission-risk'
export { monitorSepsisMarkers } from './sepsis-alert'
export { suggestBillingCodes } from './billing-suggest'
export { detectBillingAnomalies } from './fraud-detect'
export { generatePatientSummary } from './patient-summary'
export { optimizeAppointmentSlots } from './appointment-optimize'
export { predictPharmacySupply } from './supply-predict'
export { forecastBloodDemand } from './blood-demand'
export { prioritizeCSSDQueue } from './cssd-priority'
export { retrieveProtocol } from './clinical-protocol'
export { generateHandoverBrief } from './handover-brief'
export { nlpPatientSearch } from './nlp-search'
